# Generated by Django 4.2.7 on 2025-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='anonymous_likes',
            field=models.IntegerField(default=0),
        ),
    ]
